### ISSUE TITLE
DB Connection error

### ISSUE THREAD

**Issue by fredsat** [cryptopool-builders/Multi-Pool-Installer#38]
After every fresh install (Ubuntu 18.04) I get the following errors after typing `yiimp checkup` I get the following error:

```
Error Model: db_accounts
CDbConnection failed to open the DB connection: could not find driverError Model: db_algos
CDbConnection failed to open the DB connection: could not find driverError Model: db_balances
CDbConnection failed to open the DB connection: could not find driverError Model: db_balanceuser
CDbConnection failed to open the DB connection: could not find driverError Model: db_bench_chips
CDbConnection failed to open the DB connection: could not find driverError Model: db_benchmarks
CDbConnection failed to open the DB connection: could not find driverError Model: db_blocks
CDbConnection failed to open the DB connection: could not find driverError Model: db_bookmarks
CDbConnection failed to open the DB connection: could not find driverError Model: db_coins
CDbConnection failed to open the DB connection: could not find driverError Model: db_connections
CDbConnection failed to open the DB connection: could not find driverError Model: db_earnings
CDbConnection failed to open the DB connection: could not find driverError Model: db_exchange
CDbConnection failed to open the DB connection: could not find driverError Model: db_hashrate
CDbConnection failed to open the DB connection: could not find driverError Model: db_hashrenter
CDbConnection failed to open the DB connection: could not find driverError Model: db_hashstats
CDbConnection failed to open the DB connection: could not find driverError Model: db_hashuser
CDbConnection failed to open the DB connection: could not find driverError Model: db_jobs
CDbConnection failed to open the DB connection: could not find driverError Model: db_jobsubmits
CDbConnection failed to open the DB connection: could not find driverError Model: db_market_history
CDbConnection failed to open the DB connection: could not find driverError Model: db_markets
CDbConnection failed to open the DB connection: could not find driverError Model: db_mining
CDbConnection failed to open the DB connection: could not find driverError Model: db_nicehash
CDbConnection failed to open the DB connection: could not find driverError Model: db_notifications
CDbConnection failed to open the DB connection: could not find driverError Model: db_orders
CDbConnection failed to open the DB connection: could not find driverError Model: db_payouts
CDbConnection failed to open the DB connection: could not find driverError Model: db_rawcoins
CDbConnection failed to open the DB connection: could not find driverError Model: db_renters
CDbConnection failed to open the DB connection: could not find driverError Model: db_rentertxs
CDbConnection failed to open the DB connection: could not find driverError Model: db_servers
CDbConnection failed to open the DB connection: could not find driverError Model: db_services
CDbConnection failed to open the DB connection: could not find driverError Model: db_settings
CDbConnection failed to open the DB connection: could not find driverError Model: db_shares
CDbConnection failed to open the DB connection: could not find driverError Model: db_stats
CDbConnection failed to open the DB connection: could not find driverError Model: db_stratums
CDbConnection failed to open the DB connection: could not find driverError Model: db_withdraws
CDbConnection failed to open the DB connection: could not find driverError Model: db_workers
CDbConnection failed to open the DB connection: could not find driverPHP Error[2]: Attempt to read property "attributeDefaults" on null
    in file /home/crypto-data/yiimp/site/web/framework/db/ar/CActiveRecord.php at line 79
#0 /home/crypto-data/yiimp/site/web/yaamp/commands/CheckupCommand.php(181): db_coins->__construct()
#1 /home/crypto-data/yiimp/site/web/yaamp/commands/CheckupCommand.php(45): CheckupCommand->autolinkCoinsImages()
#2 /home/crypto-data/yiimp/site/web/framework/console/CConsoleCommandRunner.php(71): CheckupCommand->run()
#3 /home/crypto-data/yiimp/site/web/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run()
#4 /home/crypto-data/yiimp/site/web/framework/base/CApplication.php(185): CConsoleApplication->processRequest()
#5 /home/crypto-data/yiimp/site/web/yaamp/yiic.php(31): CConsoleApplication->run()
```

any idea? Maybe some change in `/etc/php/8.1/cli/php.ini` is needed?

**Comment by fredsat** [comment]
Solved:

`sudo apt install php8.1-mysql` then `sudo service nginx restart`

now `yiimp checkup` returns everything normal
